//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{KeyboardButton, PreparedKeyboardButton, UserId};

impl_payload! {
    /// Stores a keyboard button that can be used by a user within a Mini App. Returns a PreparedKeyboardButton object.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub SavePreparedKeyboardButton (SavePreparedKeyboardButtonSetters) => PreparedKeyboardButton {
        required {
            /// Unique identifier of the target user
            pub user_id: UserId,
            /// The button to store
            pub button: KeyboardButton,
        }
    }
}
